### ISSUE TITLE
User testing Research

### ISSUE THREAD

**Issue by JayyDex** [deco3500/TeamLumos#25]

**Comment by ytphang** [comment]
User research is an important part of User Experience Design. Typically done at the start of a project, it encompasses different types of research methodology to gather both qualitative and quantitative data in relation to our product.

Quantitative data on the other hand is generally numerical data that can be measured and analysed, looking more at the statistics. Quantitative data is used to quantify the opinions and behaviors of targeted users. First Click Testing and  A/B Testing are applied for this methodlogy. 

Qualitative data is descriptive data and looks more at how people think and feel. It helps to find our target users opinions, problems, reasons and motivations. Interview method is applied for this methodology. 

Each interview and testings aimed to draw out the flaws within the product. Each interview was
conducted with one interviewer and one target user of the product. Interviewee will be given a picture showing the general design and functionlities of NewsTruck follow by a few questions. 

1) We will observe the order of interviewee click on when they were given the picture (Diagram 1.0)the screen design without any explainations of the use of product.

Diagram 1.0:
![14315969_10210002253950111_638425513_o](https://cloud.githubusercontent.com/assets/12644555/19152678/860d86a6-8c16-11e6-81b1-068d095a3f21.png)

Most interviewee go in the order of Popular Headline article -> Top comments 
Small amount of intervieww go in the order of Side Topic -> comments section

2) We explain the general idea of NewsTruck, and ask a few specific questions (Responses are summarized accordingly as below):
- Will you approach NewsTruck?
  [Response 1] Depends on location (spacious, easy access, under shade, nearby) 
  [Response 2] Yes! (free Wi-Fi, free gifts)
  [Response 3] Depends on incentives
- How do you think public will interact with NewsTruck?
  [Response 1] Leech free Wi-Fi
  [Response 2] Some might take it seriously but most people might use it as a joke
  [Response 3] It could possibly get people out to socialise around and find out local news
- What do you like best about this product?
  [Response 1] It's a quite original idea, at least not commonly seen (mysterious news truck which appears out of no where)
  [Response 2] Giving out free stuffs (voucher, Wi-Fi)
- What do you think can be improved?
  [Response 1] Notification for type of incentives to attract and motivate people to approach
  [Response 2] Other topics need bigger picture to attract readers
  [Response 3] Quite difficult for people who wants to read comment without downloading the application. 
  [Response 4] The board could only interact by limited people at once in a public space, probably a bigger board will be needed.

3) Mobile application design (Diagram2.0) for NewsTruck also presented to interviewee and responses were summarised as below:

Diagram 2.0: 
![full2](https://cloud.githubusercontent.com/assets/12644555/19153425/e3a5d0e0-8c19-11e6-9600-0f8c6ec28f72.png)
- What do you think can be improved?
  [Response 1] Overall looks OK, personal page looks a bit empty
  [Response 2] Scanning page does not look attaractive
  [Response 3] Not quite sure what coming after scanning page, a more detail flow might be required..(UX flow)
  [Response 4] Personal page is toooo empty, and button across all pages should be consistently align at the bottom (more professional?)
